export default {
  REQUEST_SUBJECTS: 'REQUEST SUBJECTS',
  RECEIVE_SUBJECTS: 'RECEIVE SUBJECTS',
  SUBMIT_SUBJECT_BEGIN: 'SUBMIT SUBJECT BEGIN',
  SUBMIT_SUBJECT_SUCCESS: 'SUBMIT SUBJECT SUCCESS',
  SUBMIT_SUBJECT_ERROR: 'SUBMIT SUBJECT ERROR',
  SUBMIT_CLASS_BEGIN: 'SUBMIT CLASS BEGIN',
  SUBMIT_CLASS_SUCCESS: 'SUBMIT CLASS SUCCESS',
  SUBMIT_CLASS_ERROR: 'SUBMIT CLASS ERROR'
}
