export default {
  REQUEST_SUBJECTS: 'REQUEST SUBJECTS',
  RECEIVE_SUBJECTS: 'RECEIVE SUBJECTS',
  SUBMIT_SUBJECT_BEGIN: 'SUBMIT SUBJECT BEGIN',
  SUBMIT_SUBJECT_SUCCESS: 'SUBMIT SUBJECT SUCCESS',
  SUBMIT_SUBJECT_ERROR: 'SUBMIT SUBJECT ERROR'
}
