export const SUBMIT_TEACHER_BEGIN = 'SUBMIT TEACHER BEGIN'
export const SUBMIT_TEACHER_SUCCESS = 'SUBMIT TEACHER SUCCESS'
export const SUBMIT_TEACHER_FAIL = 'SUBMIT TEACHER FAIL'

export const ADD_TEACHER = 'ADD TEACHER'
export const REMOVE_TEACHER = 'REMOVE TEACHER'

export const RESET_TEACHER = 'RESET TEACHER'
